apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kubia
  name: kubia
spec:
  containers:
  - image: 745655567840.dkr.ecr.us-east-1.amazonaws.com/niluxsi-repo:v0.1
    name: kubia
    env:
    - name: DBPORT
      value: "3307"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
