apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: 745655567840.dkr.ecr.us-east-1.amazonaws.com/niluxsi-repo:v0.1
          name: kubia
          env:
            - name: DBPORT
              value: "3307"
          resources: {}
